/*
 * Copyright (c) 2018, Commonwealth Scientific and Industrial Research
 * Organisation (CSIRO)
 * All rights reserved.
 */

/**
 *      THIS FILE WAS AUTOGENERATED ON 05/30/2020, 00:39:44 from gatt.xml.
 * 
 *      THE PURPOSE OF THIS FILE IS SOLELY TO INTIALISE THE GATT TABLE. 
 **/

/* Includes -------------------------------------------------*/

#include "ble.h"

#include "bluetooth_gatt.h"

#include "log.h"

/* Private Defines ------------------------------------------*/
// clang-format off

// clang-format on

/* Type Definitions -----------------------------------------*/

/* Function Declarations ------------------------------------*/

static eModuleError_t service_device_information( void );
static eModuleError_t characteristic_manufacturer_name_string( uint16_t usServiceHandle );
static eModuleError_t characteristic_model_number_string( uint16_t usServiceHandle );
static eModuleError_t characteristic_firmware_revision_string( uint16_t usServiceHandle );
static eModuleError_t service_csiro_payloads( void );
static eModuleError_t characteristic_csiro_in( uint16_t usServiceHandle );
static eModuleError_t characteristic_csiro_out_acked( uint16_t usServiceHandle );
static eModuleError_t characteristic_csiro_out_nacked( uint16_t usServiceHandle );

/* Attribute Handles ----------------------------------------*/

uint16_t gattdb_device_information;
uint16_t gattdb_manufacturer_name_string;
uint16_t gattdb_model_number_string;
uint16_t gattdb_firmware_revision_string;
uint16_t gattdb_csiro_payloads;
uint16_t gattdb_csiro_in;
uint16_t gattdb_csiro_out_acked;
uint16_t gattdb_csiro_out_nacked;

uint16_t *ppusGattProfileHandles[] = {
	&gattdb_device_information,
	&gattdb_manufacturer_name_string,
	&gattdb_model_number_string,
	&gattdb_firmware_revision_string,
	&gattdb_csiro_payloads,
	&gattdb_csiro_in,
	&gattdb_csiro_out_acked,
	&gattdb_csiro_out_nacked,
	NULL
};

/* Private Variables ----------------------------------------*/

/*-----------------------------------------------------------*/

eModuleError_t eGattInit( void )
{
service_device_information();
service_csiro_payloads();
	return ERROR_NONE;
}

/*-----------------------------------------------------------*/

static eModuleError_t service_device_information( void )
{
	ble_uuid_t xServiceUUID = { .uuid = 0x180A, .type = BLE_UUID_TYPE_BLE };
	uint32_t   ulErrCode;

	ulErrCode = sd_ble_gatts_service_add( BLE_GATTS_SRVC_TYPE_PRIMARY, &xServiceUUID, &gattdb_device_information );
	eLog( LOG_BLUETOOTH_GATT, LOG_VERBOSE, "SERVICE_ADD: Handle=%d %d\r\n", gattdb_device_information, ulErrCode );

    characteristic_manufacturer_name_string( gattdb_device_information );
    characteristic_model_number_string( gattdb_device_information );
    characteristic_firmware_revision_string( gattdb_device_information );

    return ERROR_NONE;
}

/*-----------------------------------------------------------*/

static eModuleError_t characteristic_manufacturer_name_string( uint16_t usServiceHandle )
{
	ble_uuid_t				 xCharUUID = { .uuid = 0x2A29, .type = BLE_UUID_TYPE_BLE };
	ble_gatts_char_handles_t xCharHandles;
	uint32_t				 ulErrCode;

	/* Client Characteristic Configuration Description */
	ble_gatts_attr_md_t xCharMetadataCCCD;
	pvMemset( &xCharMetadataCCCD, 0x00, sizeof( ble_gatts_attr_md_t ) );
	xCharMetadataCCCD.vloc = BLE_GATTS_VLOC_STACK;
	BLE_GAP_CONN_SEC_MODE_SET_OPEN( &xCharMetadataCCCD.read_perm );
	BLE_GAP_CONN_SEC_MODE_SET_OPEN( &xCharMetadataCCCD.write_perm );

	/* Characteristic Description */
	ble_gatts_char_md_t xCharacteristicSettings;
	pvMemset( &xCharacteristicSettings, 0x00, sizeof( ble_gatts_char_md_t ) );

	xCharacteristicSettings.char_props.indicate = false;
	xCharacteristicSettings.char_props.notify = false;
	xCharacteristicSettings.char_ext_props.reliable_wr = false;
	xCharacteristicSettings.char_props.read = true;
	xCharacteristicSettings.char_props.write = false;
	xCharacteristicSettings.char_props.write_wo_resp = false;
	xCharacteristicSettings.p_char_user_desc		 = NULL;
	xCharacteristicSettings.p_char_pf				 = NULL;
	xCharacteristicSettings.p_user_desc_md			 = NULL;
	xCharacteristicSettings.p_cccd_md				 = &xCharMetadataCCCD;
	xCharacteristicSettings.p_sccd_md				 = NULL;

	/* Characteristic Value Metadata */
	ble_gatts_attr_md_t xCharMetadataAttr;
	pvMemset( &xCharMetadataAttr, 0x00, sizeof( ble_gatts_attr_md_t ) );
	BLE_GAP_CONN_SEC_MODE_SET_OPEN( &xCharMetadataAttr.read_perm );
	BLE_GAP_CONN_SEC_MODE_SET_OPEN( &xCharMetadataAttr.write_perm );

	xCharMetadataAttr.vloc	= BLE_GATTS_VLOC_STACK;
	xCharMetadataAttr.rd_auth = 0;
	xCharMetadataAttr.wr_auth = 0;
	xCharMetadataAttr.vlen = false;

	/* Characteristic Value */
	ble_gatts_attr_t xCharValue;

	pvMemset( &xCharValue, 0, sizeof( ble_gatts_attr_t ) );

	xCharValue.p_uuid	= &xCharUUID;
	xCharValue.p_attr_md = &xCharMetadataAttr;
	xCharValue.init_len  = 0;
	xCharValue.init_offs = 0;
	xCharValue.max_len = 5;
	xCharValue.p_value = (uint8_t *) "CSIRO";
	
	ulErrCode = sd_ble_gatts_characteristic_add( usServiceHandle,
												 &xCharacteristicSettings,
												 &xCharValue,
												 &xCharHandles );
	eLog( LOG_BLUETOOTH_GATT, LOG_VERBOSE, "CHAR_ADD: Handle=%d %d\r\n", xCharHandles.value_handle, ulErrCode );
	gattdb_manufacturer_name_string = xCharHandles.value_handle;
	return ( ulErrCode == NRF_SUCCESS ) ? ERROR_NONE : ERROR_INITIALISATION_FAILURE;
}

/*-----------------------------------------------------------*/

static eModuleError_t characteristic_model_number_string( uint16_t usServiceHandle )
{
	ble_uuid_t				 xCharUUID = { .uuid = 0x2A24, .type = BLE_UUID_TYPE_BLE };
	ble_gatts_char_handles_t xCharHandles;
	uint32_t				 ulErrCode;

	/* Client Characteristic Configuration Description */
	ble_gatts_attr_md_t xCharMetadataCCCD;
	pvMemset( &xCharMetadataCCCD, 0x00, sizeof( ble_gatts_attr_md_t ) );
	xCharMetadataCCCD.vloc = BLE_GATTS_VLOC_STACK;
	BLE_GAP_CONN_SEC_MODE_SET_OPEN( &xCharMetadataCCCD.read_perm );
	BLE_GAP_CONN_SEC_MODE_SET_OPEN( &xCharMetadataCCCD.write_perm );

	/* Characteristic Description */
	ble_gatts_char_md_t xCharacteristicSettings;
	pvMemset( &xCharacteristicSettings, 0x00, sizeof( ble_gatts_char_md_t ) );

	xCharacteristicSettings.char_props.indicate = false;
	xCharacteristicSettings.char_props.notify = false;
	xCharacteristicSettings.char_ext_props.reliable_wr = false;
	xCharacteristicSettings.char_props.read = true;
	xCharacteristicSettings.char_props.write = false;
	xCharacteristicSettings.char_props.write_wo_resp = false;
	xCharacteristicSettings.p_char_user_desc		 = NULL;
	xCharacteristicSettings.p_char_pf				 = NULL;
	xCharacteristicSettings.p_user_desc_md			 = NULL;
	xCharacteristicSettings.p_cccd_md				 = &xCharMetadataCCCD;
	xCharacteristicSettings.p_sccd_md				 = NULL;

	/* Characteristic Value Metadata */
	ble_gatts_attr_md_t xCharMetadataAttr;
	pvMemset( &xCharMetadataAttr, 0x00, sizeof( ble_gatts_attr_md_t ) );
	BLE_GAP_CONN_SEC_MODE_SET_OPEN( &xCharMetadataAttr.read_perm );
	BLE_GAP_CONN_SEC_MODE_SET_OPEN( &xCharMetadataAttr.write_perm );

	xCharMetadataAttr.vloc	= BLE_GATTS_VLOC_STACK;
	xCharMetadataAttr.rd_auth = 0;
	xCharMetadataAttr.wr_auth = 0;
	xCharMetadataAttr.vlen = true;

	/* Characteristic Value */
	ble_gatts_attr_t xCharValue;

	pvMemset( &xCharValue, 0, sizeof( ble_gatts_attr_t ) );

	xCharValue.p_uuid	= &xCharUUID;
	xCharValue.p_attr_md = &xCharMetadataAttr;
	xCharValue.init_len  = 0;
	xCharValue.init_offs = 0;
	xCharValue.max_len = 15;
	xCharValue.p_value = NULL;
	
	ulErrCode = sd_ble_gatts_characteristic_add( usServiceHandle,
												 &xCharacteristicSettings,
												 &xCharValue,
												 &xCharHandles );
	eLog( LOG_BLUETOOTH_GATT, LOG_VERBOSE, "CHAR_ADD: Handle=%d %d\r\n", xCharHandles.value_handle, ulErrCode );
	gattdb_model_number_string = xCharHandles.value_handle;
	return ( ulErrCode == NRF_SUCCESS ) ? ERROR_NONE : ERROR_INITIALISATION_FAILURE;
}

/*-----------------------------------------------------------*/

static eModuleError_t characteristic_firmware_revision_string( uint16_t usServiceHandle )
{
	ble_uuid_t				 xCharUUID = { .uuid = 0x2A26, .type = BLE_UUID_TYPE_BLE };
	ble_gatts_char_handles_t xCharHandles;
	uint32_t				 ulErrCode;

	/* Client Characteristic Configuration Description */
	ble_gatts_attr_md_t xCharMetadataCCCD;
	pvMemset( &xCharMetadataCCCD, 0x00, sizeof( ble_gatts_attr_md_t ) );
	xCharMetadataCCCD.vloc = BLE_GATTS_VLOC_STACK;
	BLE_GAP_CONN_SEC_MODE_SET_OPEN( &xCharMetadataCCCD.read_perm );
	BLE_GAP_CONN_SEC_MODE_SET_OPEN( &xCharMetadataCCCD.write_perm );

	/* Characteristic Description */
	ble_gatts_char_md_t xCharacteristicSettings;
	pvMemset( &xCharacteristicSettings, 0x00, sizeof( ble_gatts_char_md_t ) );

	xCharacteristicSettings.char_props.indicate = false;
	xCharacteristicSettings.char_props.notify = false;
	xCharacteristicSettings.char_ext_props.reliable_wr = false;
	xCharacteristicSettings.char_props.read = true;
	xCharacteristicSettings.char_props.write = false;
	xCharacteristicSettings.char_props.write_wo_resp = false;
	xCharacteristicSettings.p_char_user_desc		 = NULL;
	xCharacteristicSettings.p_char_pf				 = NULL;
	xCharacteristicSettings.p_user_desc_md			 = NULL;
	xCharacteristicSettings.p_cccd_md				 = &xCharMetadataCCCD;
	xCharacteristicSettings.p_sccd_md				 = NULL;

	/* Characteristic Value Metadata */
	ble_gatts_attr_md_t xCharMetadataAttr;
	pvMemset( &xCharMetadataAttr, 0x00, sizeof( ble_gatts_attr_md_t ) );
	BLE_GAP_CONN_SEC_MODE_SET_OPEN( &xCharMetadataAttr.read_perm );
	BLE_GAP_CONN_SEC_MODE_SET_OPEN( &xCharMetadataAttr.write_perm );

	xCharMetadataAttr.vloc	= BLE_GATTS_VLOC_STACK;
	xCharMetadataAttr.rd_auth = 0;
	xCharMetadataAttr.wr_auth = 0;
	xCharMetadataAttr.vlen = true;

	/* Characteristic Value */
	ble_gatts_attr_t xCharValue;

	pvMemset( &xCharValue, 0, sizeof( ble_gatts_attr_t ) );

	xCharValue.p_uuid	= &xCharUUID;
	xCharValue.p_attr_md = &xCharMetadataAttr;
	xCharValue.init_len  = 0;
	xCharValue.init_offs = 0;
	xCharValue.max_len = 7;
	xCharValue.p_value = NULL;
	
	ulErrCode = sd_ble_gatts_characteristic_add( usServiceHandle,
												 &xCharacteristicSettings,
												 &xCharValue,
												 &xCharHandles );
	eLog( LOG_BLUETOOTH_GATT, LOG_VERBOSE, "CHAR_ADD: Handle=%d %d\r\n", xCharHandles.value_handle, ulErrCode );
	gattdb_firmware_revision_string = xCharHandles.value_handle;
	return ( ulErrCode == NRF_SUCCESS ) ? ERROR_NONE : ERROR_INITIALISATION_FAILURE;
}

/*-----------------------------------------------------------*/

static eModuleError_t service_csiro_payloads( void )
{
	ble_uuid_t			xServiceUUID = { .uuid = 0x0001, .type = BLE_UUID_TYPE_UNKNOWN };
	const ble_uuid128_t	xBaseUUID	= { .uuid128={ 0x97, 0x95, 0x94, 0x93, 0x55, 0x0d, 0x95, 0x0c, 0x61, 0x0d, 0x17, 0xc5, 0x01, 0x00, 0xc9, 0x9a } };
	uint32_t			ulErrCode;

	/* Add our service to the softdevice */
	ulErrCode = sd_ble_uuid_vs_add( &xBaseUUID, &xServiceUUID.type );
	eLog( LOG_BLUETOOTH_GATT, LOG_VERBOSE, "VS_ADD: %d\r\n", ulErrCode );
	ulErrCode = sd_ble_gatts_service_add( BLE_GATTS_SRVC_TYPE_PRIMARY, &xServiceUUID, &gattdb_csiro_payloads );
	eLog( LOG_BLUETOOTH_GATT, LOG_VERBOSE, "SERVICE_ADD: Handle=%d %d\r\n", gattdb_csiro_payloads, ulErrCode );

    characteristic_csiro_in( gattdb_csiro_payloads );
    characteristic_csiro_out_acked( gattdb_csiro_payloads );
    characteristic_csiro_out_nacked( gattdb_csiro_payloads );

    return ERROR_NONE;
}

/*-----------------------------------------------------------*/

static eModuleError_t characteristic_csiro_in( uint16_t usServiceHandle )
{
	ble_uuid_t					xCharUUID = { .uuid = 0x0002, .type = BLE_UUID_TYPE_UNKNOWN };
	const ble_uuid128_t			xBaseUUID = { .uuid128={ 0x97, 0x95, 0x94, 0x93, 0x55, 0x0d, 0x95, 0x0c, 0x61, 0x0d, 0x17, 0xc5, 0x02, 0x00, 0xc9, 0x9a } };
	ble_gatts_char_handles_t	xCharHandles;
	uint32_t					ulErrCode;

	/* Add our command characteristic to the softdevice */
	ulErrCode = sd_ble_uuid_vs_add( &xBaseUUID, &xCharUUID.type );
	eLog( LOG_BLUETOOTH_GATT, LOG_VERBOSE, "VS_ADD: %d\r\n", ulErrCode );
	/* Client Characteristic Configuration Description */
	ble_gatts_attr_md_t xCharMetadataCCCD;
	pvMemset( &xCharMetadataCCCD, 0x00, sizeof( ble_gatts_attr_md_t ) );
	xCharMetadataCCCD.vloc = BLE_GATTS_VLOC_STACK;
	BLE_GAP_CONN_SEC_MODE_SET_OPEN( &xCharMetadataCCCD.read_perm );
	BLE_GAP_CONN_SEC_MODE_SET_OPEN( &xCharMetadataCCCD.write_perm );

	/* Characteristic Description */
	ble_gatts_char_md_t xCharacteristicSettings;
	pvMemset( &xCharacteristicSettings, 0x00, sizeof( ble_gatts_char_md_t ) );

	xCharacteristicSettings.char_props.indicate = false;
	xCharacteristicSettings.char_props.notify = false;
	xCharacteristicSettings.char_ext_props.reliable_wr = false;
	xCharacteristicSettings.char_props.read = false;
	xCharacteristicSettings.char_props.write = true;
	xCharacteristicSettings.char_props.write_wo_resp = true;
	xCharacteristicSettings.p_char_user_desc		 = NULL;
	xCharacteristicSettings.p_char_pf				 = NULL;
	xCharacteristicSettings.p_user_desc_md			 = NULL;
	xCharacteristicSettings.p_cccd_md				 = &xCharMetadataCCCD;
	xCharacteristicSettings.p_sccd_md				 = NULL;

	/* Characteristic Value Metadata */
	ble_gatts_attr_md_t xCharMetadataAttr;
	pvMemset( &xCharMetadataAttr, 0x00, sizeof( ble_gatts_attr_md_t ) );
	BLE_GAP_CONN_SEC_MODE_SET_OPEN( &xCharMetadataAttr.read_perm );
	BLE_GAP_CONN_SEC_MODE_SET_OPEN( &xCharMetadataAttr.write_perm );

	xCharMetadataAttr.vloc	= BLE_GATTS_VLOC_STACK;
	xCharMetadataAttr.rd_auth = 0;
	xCharMetadataAttr.wr_auth = 0;
	xCharMetadataAttr.vlen = true;

	/* Characteristic Value */
	ble_gatts_attr_t xCharValue;

	pvMemset( &xCharValue, 0, sizeof( ble_gatts_attr_t ) );

	xCharValue.p_uuid	= &xCharUUID;
	xCharValue.p_attr_md = &xCharMetadataAttr;
	xCharValue.init_len  = 0;
	xCharValue.init_offs = 0;
	xCharValue.max_len = 160;
	xCharValue.p_value = NULL;
	
	ulErrCode = sd_ble_gatts_characteristic_add( usServiceHandle,
												 &xCharacteristicSettings,
												 &xCharValue,
												 &xCharHandles );
	eLog( LOG_BLUETOOTH_GATT, LOG_VERBOSE, "CHAR_ADD: Handle=%d %d\r\n", xCharHandles.value_handle, ulErrCode );
	gattdb_csiro_in = xCharHandles.value_handle;
	return ( ulErrCode == NRF_SUCCESS ) ? ERROR_NONE : ERROR_INITIALISATION_FAILURE;
}

/*-----------------------------------------------------------*/

static eModuleError_t characteristic_csiro_out_acked( uint16_t usServiceHandle )
{
	ble_uuid_t					xCharUUID = { .uuid = 0x0003, .type = BLE_UUID_TYPE_UNKNOWN };
	const ble_uuid128_t			xBaseUUID = { .uuid128={ 0x97, 0x95, 0x94, 0x93, 0x55, 0x0d, 0x95, 0x0c, 0x61, 0x0d, 0x17, 0xc5, 0x03, 0x00, 0xc9, 0x9a } };
	ble_gatts_char_handles_t	xCharHandles;
	uint32_t					ulErrCode;

	/* Add our command characteristic to the softdevice */
	ulErrCode = sd_ble_uuid_vs_add( &xBaseUUID, &xCharUUID.type );
	eLog( LOG_BLUETOOTH_GATT, LOG_VERBOSE, "VS_ADD: %d\r\n", ulErrCode );
	/* Client Characteristic Configuration Description */
	ble_gatts_attr_md_t xCharMetadataCCCD;
	pvMemset( &xCharMetadataCCCD, 0x00, sizeof( ble_gatts_attr_md_t ) );
	xCharMetadataCCCD.vloc = BLE_GATTS_VLOC_STACK;
	BLE_GAP_CONN_SEC_MODE_SET_OPEN( &xCharMetadataCCCD.read_perm );
	BLE_GAP_CONN_SEC_MODE_SET_OPEN( &xCharMetadataCCCD.write_perm );

	/* Characteristic Description */
	ble_gatts_char_md_t xCharacteristicSettings;
	pvMemset( &xCharacteristicSettings, 0x00, sizeof( ble_gatts_char_md_t ) );

	xCharacteristicSettings.char_props.indicate = true;
	xCharacteristicSettings.char_props.notify = false;
	xCharacteristicSettings.char_ext_props.reliable_wr = false;
	xCharacteristicSettings.char_props.read = false;
	xCharacteristicSettings.char_props.write = false;
	xCharacteristicSettings.char_props.write_wo_resp = false;
	xCharacteristicSettings.p_char_user_desc		 = NULL;
	xCharacteristicSettings.p_char_pf				 = NULL;
	xCharacteristicSettings.p_user_desc_md			 = NULL;
	xCharacteristicSettings.p_cccd_md				 = &xCharMetadataCCCD;
	xCharacteristicSettings.p_sccd_md				 = NULL;

	/* Characteristic Value Metadata */
	ble_gatts_attr_md_t xCharMetadataAttr;
	pvMemset( &xCharMetadataAttr, 0x00, sizeof( ble_gatts_attr_md_t ) );
	BLE_GAP_CONN_SEC_MODE_SET_OPEN( &xCharMetadataAttr.read_perm );
	BLE_GAP_CONN_SEC_MODE_SET_OPEN( &xCharMetadataAttr.write_perm );

	xCharMetadataAttr.vloc	= BLE_GATTS_VLOC_STACK;
	xCharMetadataAttr.rd_auth = 0;
	xCharMetadataAttr.wr_auth = 0;
	xCharMetadataAttr.vlen = true;

	/* Characteristic Value */
	ble_gatts_attr_t xCharValue;

	pvMemset( &xCharValue, 0, sizeof( ble_gatts_attr_t ) );

	xCharValue.p_uuid	= &xCharUUID;
	xCharValue.p_attr_md = &xCharMetadataAttr;
	xCharValue.init_len  = 0;
	xCharValue.init_offs = 0;
	xCharValue.max_len = 160;
	xCharValue.p_value = NULL;
	
	ulErrCode = sd_ble_gatts_characteristic_add( usServiceHandle,
												 &xCharacteristicSettings,
												 &xCharValue,
												 &xCharHandles );
	eLog( LOG_BLUETOOTH_GATT, LOG_VERBOSE, "CHAR_ADD: Handle=%d %d\r\n", xCharHandles.value_handle, ulErrCode );
	gattdb_csiro_out_acked = xCharHandles.value_handle;
	return ( ulErrCode == NRF_SUCCESS ) ? ERROR_NONE : ERROR_INITIALISATION_FAILURE;
}

/*-----------------------------------------------------------*/

static eModuleError_t characteristic_csiro_out_nacked( uint16_t usServiceHandle )
{
	ble_uuid_t					xCharUUID = { .uuid = 0x0004, .type = BLE_UUID_TYPE_UNKNOWN };
	const ble_uuid128_t			xBaseUUID = { .uuid128={ 0x97, 0x95, 0x94, 0x93, 0x55, 0x0d, 0x95, 0x0c, 0x61, 0x0d, 0x17, 0xc5, 0x04, 0x00, 0xc9, 0x9a } };
	ble_gatts_char_handles_t	xCharHandles;
	uint32_t					ulErrCode;

	/* Add our command characteristic to the softdevice */
	ulErrCode = sd_ble_uuid_vs_add( &xBaseUUID, &xCharUUID.type );
	eLog( LOG_BLUETOOTH_GATT, LOG_VERBOSE, "VS_ADD: %d\r\n", ulErrCode );
	/* Client Characteristic Configuration Description */
	ble_gatts_attr_md_t xCharMetadataCCCD;
	pvMemset( &xCharMetadataCCCD, 0x00, sizeof( ble_gatts_attr_md_t ) );
	xCharMetadataCCCD.vloc = BLE_GATTS_VLOC_STACK;
	BLE_GAP_CONN_SEC_MODE_SET_OPEN( &xCharMetadataCCCD.read_perm );
	BLE_GAP_CONN_SEC_MODE_SET_OPEN( &xCharMetadataCCCD.write_perm );

	/* Characteristic Description */
	ble_gatts_char_md_t xCharacteristicSettings;
	pvMemset( &xCharacteristicSettings, 0x00, sizeof( ble_gatts_char_md_t ) );

	xCharacteristicSettings.char_props.indicate = false;
	xCharacteristicSettings.char_props.notify = true;
	xCharacteristicSettings.char_ext_props.reliable_wr = false;
	xCharacteristicSettings.char_props.read = false;
	xCharacteristicSettings.char_props.write = false;
	xCharacteristicSettings.char_props.write_wo_resp = false;
	xCharacteristicSettings.p_char_user_desc		 = NULL;
	xCharacteristicSettings.p_char_pf				 = NULL;
	xCharacteristicSettings.p_user_desc_md			 = NULL;
	xCharacteristicSettings.p_cccd_md				 = &xCharMetadataCCCD;
	xCharacteristicSettings.p_sccd_md				 = NULL;

	/* Characteristic Value Metadata */
	ble_gatts_attr_md_t xCharMetadataAttr;
	pvMemset( &xCharMetadataAttr, 0x00, sizeof( ble_gatts_attr_md_t ) );
	BLE_GAP_CONN_SEC_MODE_SET_OPEN( &xCharMetadataAttr.read_perm );
	BLE_GAP_CONN_SEC_MODE_SET_OPEN( &xCharMetadataAttr.write_perm );

	xCharMetadataAttr.vloc	= BLE_GATTS_VLOC_STACK;
	xCharMetadataAttr.rd_auth = 0;
	xCharMetadataAttr.wr_auth = 0;
	xCharMetadataAttr.vlen = true;

	/* Characteristic Value */
	ble_gatts_attr_t xCharValue;

	pvMemset( &xCharValue, 0, sizeof( ble_gatts_attr_t ) );

	xCharValue.p_uuid	= &xCharUUID;
	xCharValue.p_attr_md = &xCharMetadataAttr;
	xCharValue.init_len  = 0;
	xCharValue.init_offs = 0;
	xCharValue.max_len = 160;
	xCharValue.p_value = NULL;
	
	ulErrCode = sd_ble_gatts_characteristic_add( usServiceHandle,
												 &xCharacteristicSettings,
												 &xCharValue,
												 &xCharHandles );
	eLog( LOG_BLUETOOTH_GATT, LOG_VERBOSE, "CHAR_ADD: Handle=%d %d\r\n", xCharHandles.value_handle, ulErrCode );
	gattdb_csiro_out_nacked = xCharHandles.value_handle;
	return ( ulErrCode == NRF_SUCCESS ) ? ERROR_NONE : ERROR_INITIALISATION_FAILURE;
}

/*-----------------------------------------------------------*/

