/*
 * Copyright (c) 2020, Commonwealth Scientific and Industrial Research 
 * Organisation (CSIRO) ABN 41 687 119 230.
 *
 * Filename: gatt_autogen.h
 * Author: John Scolaro
 * 
 */

#ifndef __CSIRO_CORE_GATT_AUTOGEN
#define __CSIRO_CORE_GATT_AUTOGEN

/**
 * 
 *      THIS FILE WAS AUTOGENERATED FROM gatt.xml. DO NOT MODIFY.
 *      
 *      GENERATED ON: 04/21/2020, 12:55:18
 * 
 *      PURPOSE OF THIS FILE IS TO PROVIDE AN ARCHITECTURE AGNOSTIC WAY OF
 *      ACCESSING CHARACTERISTIC HANDLES
 * 
 *      AS WE DONT WANT TO MODIFY THE FILE EFR32 GENERATES, WE WILL CONFORM TO THEIR SPEC
 * 
 *      FOR NOW WE PRETEND THAT THE APPLICATION ONLY WANTS THE GENERIC
 *      CSIRO SERVICES
 * 
 */

#include "stdint.h"

extern uint16_t gattdb_device_information;
extern uint16_t gattdb_manufacturer_name_string;
extern uint16_t gattdb_model_number_string;
extern uint16_t gattdb_firmware_revision_string;
extern uint16_t gattdb_csiro_payloads;
extern uint16_t gattdb_csiro_in;
extern uint16_t gattdb_csiro_out_acked;
extern uint16_t gattdb_csiro_out_nacked;

extern uint16_t *ppusGattProfileHandles[];

#endif /* __CSIRO_CORE_GATT_AUTOGEN */